### ISSUE TITLE
the dimension of output (output=self.dncnn(x))  don't match with the input x

### ISSUE THREAD

**Issue by DL15879104631** [scliubit/complex-DnCNN#1]
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 1

**Comment by scliubit** [comment]
now with the matlab generated dataset, you wont get that error again.

**Comment by JYang666** [comment]
x dimensions: torch.Size([2, 256, 1, 2, 100])
y dimensions: torch.Size([2, 256, 1, 2, 100])
out dimensions: torch.Size([2, 2, 1, 2, 100])
File "D:\workbench\complex-DnCNN-master\models.py", line 181, in forward
    return y - out
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 1
