### ISSUE TITLE
matlab生成数据集后仍然同样报错RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 1

### ISSUE THREAD

**Issue by JYang666** [scliubit/complex-DnCNN#2]
x dimensions: torch.Size([2, 256, 1, 2, 100])
y dimensions: torch.Size([2, 256, 1, 2, 100])
out dimensions: torch.Size([2, 2, 1, 2, 100])
File "D:\workbench\complex-DnCNN-master\models.py", line 181, in forward
return y - out
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 1

**Comment by scliubit** [comment]
感谢您的测试, 十分抱歉刚刚看到。直接拉取代码后用`TrainingSetGen.m`生成的数据集可以直接跑通。如无其他问题该issue晚些则会关闭。

Thanks for your testing, and sorry for missing this issue notification. The dataset generated by `TrainingSetGen.m` can be run without error after directly cloning the code. If there is no other questions, this issue will be closed later.
